# Generated by Django 3.2.2 on 2021-05-18 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='UserId', max_length=128, verbose_name='User')),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=4, max_digits=12, verbose_name='Balance')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallet',
                'db_table': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletEmailAdmin',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'verbose_name': 'Wallet Email Admin',
                'verbose_name_plural': 'Wallet Email Admin',
                'db_table': 'WalletEmailAdmin',
            },
        ),
        migrations.CreateModel(
            name='WalletOTPAdmin',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(db_column='MobileNo', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MaxLengthValidator(10)])),
                ('transaction_limit', models.IntegerField(db_column='TransactionLimit')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'verbose_name': 'Wallet OTP Admin',
                'verbose_name_plural': 'Wallet OTP Admin',
                'db_table': 'WalletOTPAdmin',
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_column='TransactionDate')),
                ('transaction_amount', models.DecimalField(db_column='TransactionAmount', decimal_places=4, max_digits=18)),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=4, max_digits=18)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=255, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('transaction_status', models.CharField(blank=True, db_column='TransactionStatus', max_length=10, null=True)),
                ('wallet', models.ForeignKey(db_column='WalletId', on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transactions',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'WalletTransactions',
            },
        ),
        migrations.CreateModel(
            name='StaffPartnerTransactions',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=128)),
                ('partner_id', models.CharField(max_length=128)),
                ('wallet_transaction_id', models.ForeignKey(db_column='WalletTransactionId', on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallettransactions')),
            ],
            options={
                'verbose_name': 'StaffPartnerTransaction',
                'verbose_name_plural': 'StaffPartnerTransactions',
                'db_table': 'StaffPartnerTransactions',
            },
        ),
        migrations.CreateModel(
            name='RazorpayTransactions',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, db_column='OrderId', max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, db_column='PaymentId', max_length=255, null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=4, max_digits=18)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('contact', models.CharField(db_column='ContactNo', max_length=10)),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('payment_method', models.CharField(blank=True, db_column='PaymentMethod', max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('wallet_transaction_id', models.ForeignKey(db_column='WalletTransactionId', on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallettransactions')),
            ],
            options={
                'verbose_name': 'Razorpay Transactions',
                'verbose_name_plural': 'Razorpay Transactions',
                'db_table': 'RazorpayTransactions',
            },
        ),
    ]
